travis:
  secure:
    BINSTAR_TOKEN: mrYgZTD65/Rhq5ooiia4koIlQmjTWTzaMPI2zvG7O4+j18jsUjnkwVM4oLpqtuhWruqYYUfM6ZkdvrAKE9aC0gLa36yGk6UoT4VHog40669A1zR9RGVoShW6LW3dqJf7KaxM4//w4Vew+7oDMiZcBAmsEopOFNkUQjiKayP5KBMnhoTNsNFDNmiTnDnv4BE7lZe9hpcZUt7w4mcwYNFFKPUEJisWSN6aHoZd/2ZJ6afo8XKufVfjGu4QB1juWfxZS9f9Lev5UOJq1hrSIFcDr/ygYrb2XiNiW/rI0/6YJ3bLUQ39Dwx7FhmZJ+F8FXyJ4ewGDsji/OBhHZr4RKHof8SQOKSCKkzDyZeOww5/HeYERlIMLx+ii2M1DAdlxMRsT5FhhG7tpMCkl2oO0ZtSu9V53VmIAIAofRR4aOPsOelnGGYAiMmjyTagTLKf5YHa859t9DCyqFbjT267anFaiOGp7ReOMTghJm0/m4GjtGYriWnrnRHvQZHuV98lfozon3ybWxpC8zyU1RJlscksaEfRFqaRXKS1xhWIBuEQw2LZRvaenAwG7sp2PjSNOFg2OWi5zT9UlGUNlxLSlGUxI1WiqndnqpvbMf3gQqCywc+HQ7GufKq4cnjc/iN6k9rd50XYfcoB99L6OEAAR1Qpknv9VpfufaBrP8a21hWCa8E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
